import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "38px" }}>
                This project was generated By{" "}
                <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
                    Dhiwise
                </a>
                . Quickly use the links below to navigate through all pages.
            </p>
            <ul style={{ listStyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/menu" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Menu
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        About Us
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/reservation" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Reservation
                    </Link>
                </li>
                <li style={{ marginBottom: "18px" }}>
                    <Link to="/contact" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Contact
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/orderonline" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Orderonline
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/checkout" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Checkout
                    </Link>
                </li>
                <li style={{ marginBottom: "18px" }}>
                    <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Homepage
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;